spring:
  application:
    name: gcp

  datasource:
    url: jdbc:postgresql://localhost:5432/delivery
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

#  flyway:
#    baseline-on-migrate: true
#    enabled: true
#    validate-on-migrate: true
#    baseline-version: 0

server:
  port: 8000
